"""CLI commands for WB Finance API — sales-reports and acquiring.

Settlement reports are pre-generated by WB on a weekly schedule (daily
when the seller has opted in). These commands wrap six read-only
endpoints — no "create" or "generate" step is needed.

Distinct from sibling commands:

- ``wb budget balance``   — ad-deposit on ``/adv/v1/balance`` (promotion).
- ``wb report sales``     — per-sale transaction log (statistics API).
- ``wb finance …``        — settlement statements (this module).

All commands branch strictly on ``renderer.is_json`` per CLAUDE.md so
table mode receives ``list[list[str]]`` and never a list of dicts.
"""

from __future__ import annotations

import json
from dataclasses import asdict
from datetime import date as _date

import typer

from wb.cli._helpers import get_profile, get_renderer
from wb.core.constants import ExitCode
from wb.core.exceptions import WbCliError
from wb.core.output import render_table

__all__ = ['finance_app']

finance_app = typer.Typer(
    help='Settlement reports (sales, acquiring) — finance-api.wildberries.ru',
    no_args_is_help=True,
)

sales_reports_app = typer.Typer(
    help='Sales settlement reports (what WB owes after fees)',
    no_args_is_help=True,
)
acquiring_app = typer.Typer(
    help='Acquiring (card-processing) fee reports',
    no_args_is_help=True,
)
finance_app.add_typer(sales_reports_app, name='sales-reports')
finance_app.add_typer(acquiring_app, name='acquiring')


# ── Period enum ──────────────────────────────────────────────────────


_VALID_PERIODS = ('weekly', 'daily')


def _validate_period(period: str | None) -> str | None:
    """Return ``period`` when valid; raise BadParameter otherwise.

    Args:
        period: User-supplied value or None.

    Returns:
        Normalised period string, or None when not provided.

    Raises:
        typer.BadParameter: When ``period`` is not in ``_VALID_PERIODS``.
    """
    if period is None:
        return None
    if period not in _VALID_PERIODS:
        raise typer.BadParameter(
            f'--period must be one of {", ".join(_VALID_PERIODS)}; got {period!r}.'
        )
    return period


def _validate_date_range(date_from: str, date_to: str) -> tuple[str, str]:
    """Ensure ``date_from``/``date_to`` parse and form a non-inverted range.

    Args:
        date_from: ISO-8601 date string.
        date_to: ISO-8601 date string.

    Returns:
        The (date_from, date_to) pair unchanged.

    Raises:
        typer.BadParameter: On parse failure or inverted range.
    """
    try:
        d_from = _date.fromisoformat(date_from)
        d_to = _date.fromisoformat(date_to)
    except ValueError as exc:
        raise typer.BadParameter(
            f'--from/--to must be YYYY-MM-DD; got from={date_from!r}, to={date_to!r}.'
        ) from exc
    if d_from > d_to:
        raise typer.BadParameter(
            f'--from {date_from} is after --to {date_to}.'
        )
    return date_from, date_to


# ── Service factory helper ────────────────────────────────────────────


def _service(profile: str | None):
    """Lazy-import factory to keep CLI startup fast."""
    from wb.services._factory import create_finance_service
    return create_finance_service(profile)


# ── Table-row builders ────────────────────────────────────────────────


_SALES_LIST_HEADERS = [
    'Report ID', 'Seller', 'From', 'To', 'Created',
    'Cur', 'Sales', 'Payout', 'Penalties', 'Bank Pay',
]

_ACQUIRING_LIST_HEADERS = [
    'Report ID', 'Seller', 'From', 'To', 'Created',
    'Cur', 'Fee', 'VAT',
]

_SALES_DETAIL_HEADERS = [
    'rrdId', 'nmId', 'Subject', 'Doc', 'Qty',
    'Sales', 'Payout', 'Date', 'srid',
]

_ACQUIRING_DETAIL_HEADERS = [
    'rrdId', 'Sale Date', 'Acq Date', 'nmId', 'Doc',
    'Sales', 'Fee', 'VAT', 'srid',
]


def _sales_summary_rows(summaries) -> list[list[str]]:
    """Convert :class:`SalesReportSummary` instances to table rows."""
    return [
        [
            str(s.report_id),
            s.seller_finance_name,
            s.date_from,
            s.date_to,
            s.create_date,
            s.currency,
            s.retail_amount_sum,
            s.for_pay_sum,
            s.penalty_sum,
            s.bank_payment_sum,
        ]
        for s in summaries
    ]


def _acquiring_summary_rows(summaries) -> list[list[str]]:
    """Convert :class:`AcquiringReportSummary` instances to table rows."""
    return [
        [
            str(s.report_id),
            s.seller_finance_name,
            s.date_from,
            s.date_to,
            s.create_date,
            s.currency,
            s.acquiring_fee_sum,
            s.acquiring_fee_vat_sum,
        ]
        for s in summaries
    ]


def _sales_detail_rows(rows: list[dict]) -> list[list[str]]:
    """Convert raw sales-detail dicts to a compact table row set."""
    return [
        [
            str(r.get('rrdId', '')),
            str(r.get('nmId', '')),
            str(r.get('subjectName', '') or ''),
            str(r.get('docTypeName', '') or ''),
            str(r.get('quantity', 0)),
            str(r.get('retailAmount', '') or '0'),
            str(r.get('forPay', '') or '0'),
            str(r.get('rrDate', '') or r.get('saleDt', '') or ''),
            str(r.get('srid', '') or ''),
        ]
        for r in rows
    ]


def _acquiring_detail_rows(rows: list[dict]) -> list[list[str]]:
    """Convert raw acquiring-detail dicts to a compact table row set."""
    return [
        [
            str(r.get('rrdId', '')),
            str(r.get('saleDate', '') or ''),
            str(r.get('acqDate', '') or ''),
            str(r.get('nmId', '')),
            str(r.get('docTypeName', '') or ''),
            str(r.get('retailAmount', '') or '0'),
            str(r.get('acquiringFee', '') or '0'),
            str(r.get('acquiringFeeVat', '') or '0'),
            str(r.get('srid', '') or ''),
        ]
        for r in rows
    ]


# ── sales-reports list ────────────────────────────────────────────────


@sales_reports_app.command('list')
def sales_reports_list(
        ctx: typer.Context,
        date_from: str = typer.Option(
            ..., '--from', help='Reporting period start (YYYY-MM-DD).',
        ),
        date_to: str = typer.Option(
            ..., '--to', help='Reporting period end (YYYY-MM-DD).',
        ),
        period: str | None = typer.Option(
            None, '--period',
            help='Report periodicity: weekly (default) or daily.',
        ),
        limit: int = typer.Option(
            1000, '--limit', help='Number of reports in the response (max 1000).',
        ),
        offset: int = typer.Option(
            0, '--offset', help='How many results to skip.',
        ),
) -> None:
    """List sales-settlement report headers (one row per WB report).

    Calls ``POST /api/finance/v1/sales-reports/list``. Each row is a
    summary of one settlement statement WB generated for the seller —
    no line items here; use ``wb finance sales-reports detailed`` for
    those.
    """
    renderer = get_renderer(ctx)
    _validate_date_range(date_from, date_to)
    period = _validate_period(period)

    try:
        svc = _service(get_profile(ctx))
        summaries = svc.list_sales_reports(
            date_from=date_from,
            date_to=date_to,
            period=period,
            limit=limit,
            offset=offset,
        )
    except WbCliError as exc:
        renderer.error(str(exc))
        raise typer.Exit(code=ExitCode.API_ERROR) from exc

    if renderer.is_json:
        typer.echo(json.dumps(
            [asdict(s) for s in summaries],
            indent=2, ensure_ascii=False, default=str,
        ))
        return

    if not summaries:
        typer.echo(f'No sales reports for {date_from} … {date_to}.')
        return

    render_table(
        _SALES_LIST_HEADERS,
        _sales_summary_rows(summaries),
        title=f'Sales reports — {date_from} … {date_to} ({len(summaries)} reports)',
    )


# ── sales-reports get (by ID) ─────────────────────────────────────────


@sales_reports_app.command('get')
def sales_reports_get(
        ctx: typer.Context,
        report_id: int = typer.Argument(..., help='WB sales-report ID.'),
        limit: int = typer.Option(
            100_000, '--limit', help='Rows per API page (max 100 000).',
        ),
        fetch_all: bool = typer.Option(
            False, '--all',
            help=(
                'Exhaust the rrdId cursor. Throttled at 1 req/min — '
                'expect >=1 minute per 100 000 rows.'
            ),
        ),
) -> None:
    """Detail rows for one specific sales report.

    Calls ``POST /api/finance/v1/sales-reports/detailed/{reportId}``.
    """
    renderer = get_renderer(ctx)

    try:
        svc = _service(get_profile(ctx))
        rows = svc.sales_report_by_id(
            report_id, limit=limit, fetch_all=fetch_all,
        )
    except WbCliError as exc:
        renderer.error(str(exc))
        raise typer.Exit(code=ExitCode.API_ERROR) from exc

    if renderer.is_json:
        typer.echo(json.dumps(rows, indent=2, ensure_ascii=False, default=str))
        return

    if not rows:
        typer.echo(f'No detail rows for sales report {report_id}.')
        return

    render_table(
        _SALES_DETAIL_HEADERS,
        _sales_detail_rows(rows),
        title=f'Sales report {report_id} — {len(rows)} rows',
    )


# ── sales-reports detailed (by period) ────────────────────────────────


@sales_reports_app.command('detailed')
def sales_reports_detailed(
        ctx: typer.Context,
        date_from: str = typer.Option(
            ..., '--from', help='Reporting period start (YYYY-MM-DD).',
        ),
        date_to: str = typer.Option(
            ..., '--to', help='Reporting period end (YYYY-MM-DD).',
        ),
        period: str | None = typer.Option(
            None, '--period',
            help='Report periodicity: weekly (default) or daily.',
        ),
        limit: int = typer.Option(
            100_000, '--limit', help='Rows per API page (max 100 000).',
        ),
        fetch_all: bool = typer.Option(
            False, '--all',
            help=(
                'Exhaust the rrdId cursor across all pages. Throttled at '
                '1 req/min — expect >=1 minute per 100 000 rows.'
            ),
        ),
) -> None:
    """Detail rows across every sales report overlapping a date range.

    Calls ``POST /api/finance/v1/sales-reports/detailed``. This is the
    most common agent path — one call returns line items across any
    reports inside ``[date_from, date_to]``.
    """
    renderer = get_renderer(ctx)
    _validate_date_range(date_from, date_to)
    period = _validate_period(period)

    try:
        svc = _service(get_profile(ctx))
        rows = svc.detailed_sales_reports(
            date_from=date_from,
            date_to=date_to,
            period=period,
            limit=limit,
            fetch_all=fetch_all,
        )
    except WbCliError as exc:
        renderer.error(str(exc))
        raise typer.Exit(code=ExitCode.API_ERROR) from exc

    if renderer.is_json:
        typer.echo(json.dumps(rows, indent=2, ensure_ascii=False, default=str))
        return

    if not rows:
        typer.echo(f'No detail rows for {date_from} … {date_to}.')
        return

    render_table(
        _SALES_DETAIL_HEADERS,
        _sales_detail_rows(rows),
        title=f'Sales detail — {date_from} … {date_to} ({len(rows)} rows)',
    )


# ── acquiring list ────────────────────────────────────────────────────


@acquiring_app.command('list')
def acquiring_list(
        ctx: typer.Context,
        date_from: str = typer.Option(
            ..., '--from', help='Reporting period start (YYYY-MM-DD).',
        ),
        date_to: str = typer.Option(
            ..., '--to', help='Reporting period end (YYYY-MM-DD).',
        ),
        limit: int = typer.Option(
            1000, '--limit', help='Number of reports in the response (max 1000).',
        ),
        offset: int = typer.Option(
            0, '--offset', help='How many results to skip.',
        ),
) -> None:
    """List acquiring-expense report headers.

    Calls ``POST /api/finance/v1/acquiring/list``.
    """
    renderer = get_renderer(ctx)
    _validate_date_range(date_from, date_to)

    try:
        svc = _service(get_profile(ctx))
        summaries = svc.list_acquiring_reports(
            date_from=date_from,
            date_to=date_to,
            limit=limit,
            offset=offset,
        )
    except WbCliError as exc:
        renderer.error(str(exc))
        raise typer.Exit(code=ExitCode.API_ERROR) from exc

    if renderer.is_json:
        typer.echo(json.dumps(
            [asdict(s) for s in summaries],
            indent=2, ensure_ascii=False, default=str,
        ))
        return

    if not summaries:
        typer.echo(f'No acquiring reports for {date_from} … {date_to}.')
        return

    render_table(
        _ACQUIRING_LIST_HEADERS,
        _acquiring_summary_rows(summaries),
        title=f'Acquiring reports — {date_from} … {date_to} ({len(summaries)} reports)',
    )


# ── acquiring get (by ID) ─────────────────────────────────────────────


@acquiring_app.command('get')
def acquiring_get(
        ctx: typer.Context,
        report_id: int = typer.Argument(..., help='WB acquiring-report ID.'),
        limit: int = typer.Option(
            100_000, '--limit', help='Rows per API page (max 100 000).',
        ),
        fetch_all: bool = typer.Option(
            False, '--all',
            help=(
                'Exhaust the rrdId cursor. Throttled at 1 req/min — '
                'expect >=1 minute per 100 000 rows.'
            ),
        ),
) -> None:
    """Detail rows for one specific acquiring report.

    Calls ``POST /api/finance/v1/acquiring/detailed/{reportId}``.
    """
    renderer = get_renderer(ctx)

    try:
        svc = _service(get_profile(ctx))
        rows = svc.acquiring_report_by_id(
            report_id, limit=limit, fetch_all=fetch_all,
        )
    except WbCliError as exc:
        renderer.error(str(exc))
        raise typer.Exit(code=ExitCode.API_ERROR) from exc

    if renderer.is_json:
        typer.echo(json.dumps(rows, indent=2, ensure_ascii=False, default=str))
        return

    if not rows:
        typer.echo(f'No detail rows for acquiring report {report_id}.')
        return

    render_table(
        _ACQUIRING_DETAIL_HEADERS,
        _acquiring_detail_rows(rows),
        title=f'Acquiring report {report_id} — {len(rows)} rows',
    )


# ── acquiring detailed (by period) ────────────────────────────────────


@acquiring_app.command('detailed')
def acquiring_detailed(
        ctx: typer.Context,
        date_from: str = typer.Option(
            ..., '--from', help='Reporting period start (YYYY-MM-DD).',
        ),
        date_to: str = typer.Option(
            ..., '--to', help='Reporting period end (YYYY-MM-DD).',
        ),
        limit: int = typer.Option(
            100_000, '--limit', help='Rows per API page (max 100 000).',
        ),
        fetch_all: bool = typer.Option(
            False, '--all',
            help=(
                'Exhaust the rrdId cursor across all pages. Throttled at '
                '1 req/min — expect >=1 minute per 100 000 rows.'
            ),
        ),
) -> None:
    """Detail rows across every acquiring report overlapping a date range.

    Calls ``POST /api/finance/v1/acquiring/detailed``.
    """
    renderer = get_renderer(ctx)
    _validate_date_range(date_from, date_to)

    try:
        svc = _service(get_profile(ctx))
        rows = svc.detailed_acquiring_reports(
            date_from=date_from,
            date_to=date_to,
            limit=limit,
            fetch_all=fetch_all,
        )
    except WbCliError as exc:
        renderer.error(str(exc))
        raise typer.Exit(code=ExitCode.API_ERROR) from exc

    if renderer.is_json:
        typer.echo(json.dumps(rows, indent=2, ensure_ascii=False, default=str))
        return

    if not rows:
        typer.echo(f'No acquiring detail rows for {date_from} … {date_to}.')
        return

    render_table(
        _ACQUIRING_DETAIL_HEADERS,
        _acquiring_detail_rows(rows),
        title=f'Acquiring detail — {date_from} … {date_to} ({len(rows)} rows)',
    )
